'use strict';
const assert=require('assert');
const Core=require('../app/core.js');
let count=0;function t(name,fn){fn();count++;console.log('ok',count,'-',name);}

t('version',()=>assert.strictEqual(Core.VERSION,'28.0.0'));
t('mode',()=>assert.ok(Core.MODE.includes('AGI_DISCONTINUITY')));
t('twelve domains',()=>assert.strictEqual(Core.DOMAINS.length,12));
t('eight worlds',()=>assert.strictEqual(Core.WORLDS.length,8));
t('twelve signals',()=>assert.strictEqual(Core.SIGNALS.length,12));
t('default normalization',()=>assert.strictEqual(Core.normalizeState({}).profile.householdSize,1));
t('domain score keys',()=>assert.deepStrictEqual(Object.keys(Core.domainScores(Core.DEFAULT_STATE)).sort(),Core.DOMAINS.map(x=>x.id).sort()));
t('scores bounded',()=>Object.values(Core.domainScores(Core.DEFAULT_STATE)).forEach(x=>assert.ok(x>=0&&x<=1)));
t('demo stronger than default',()=>assert.ok(Core.readinessSummary(Core.DEMO_STATE).robustFloor>Core.readinessSummary(Core.DEFAULT_STATE).robustFloor));
t('world result count',()=>assert.strictEqual(Core.worldResults(Core.DEFAULT_STATE).length,8));
t('world floors bounded',()=>Core.worldResults(Core.DEFAULT_STATE).forEach(w=>assert.ok(w.floor>=0&&w.floor<=1)));
t('robust floor is minimum',()=>{const s=Core.readinessSummary(Core.DEMO_STATE);assert.strictEqual(s.robustFloor,Math.min(...s.worlds.map(w=>w.floor)));});
t('trigger baseline',()=>assert.strictEqual(Core.triggerMode([]).level,0));
t('trigger warning',()=>assert.strictEqual(Core.triggerMode(['conflicting_sources']).level,1));
t('trigger continuity',()=>assert.ok(Core.triggerMode(['deepfake_request','communication_outage']).level>=2));
t('trigger protective isolation',()=>assert.ok(Core.triggerMode(['identity_takeover']).level>=3));
t('trigger life safety',()=>assert.strictEqual(Core.triggerMode(['immediate_life_threat']).level,4));
t('priority actions exist on default',()=>assert.ok(Core.getPriorityActions(Core.DEFAULT_STATE).length>=8));
t('demo has fewer actions',()=>assert.ok(Core.getPriorityActions(Core.DEMO_STATE).length<Core.getPriorityActions(Core.DEFAULT_STATE).length));
t('kit has ten items',()=>assert.strictEqual(Core.buildKitList(Core.DEFAULT_STATE).length,10));
t('demo kit mostly ready',()=>assert.ok(Core.buildKitList(Core.DEMO_STATE).filter(x=>x.done).length>=7));
t('message scan low',()=>assert.strictEqual(Core.scanUrgentMessage('Please review this document tomorrow.').level,'LOW'));
t('message scan high',()=>assert.strictEqual(Core.scanUrgentMessage('紧急！不要告诉家人，马上转账并发验证码。').level,'HIGH'));
t('message scan identifies secrecy',()=>assert.ok(Core.scanUrgentMessage('Keep this secret and send crypto immediately').hits.some(x=>x.id==='secrecy')));
t('local analysis allowed',()=>assert.strictEqual(Core.evaluateAiAction({type:'local_analysis'}).decision,'ALLOW_LOCAL_REVERSIBLE_ANALYSIS'));
t('money transfer held',()=>assert.ok(Core.evaluateAiAction({type:'transfer_money'}).decision.startsWith('HOLD')));
t('medical automation denied',()=>assert.strictEqual(Core.evaluateAiAction({type:'autonomous_medical_diagnosis'}).decision,'DENY'));
t('human worth ranking denied',()=>assert.strictEqual(Core.evaluateAiAction({type:'human_worth_ranking'}).decision,'DENY'));
t('critical action remains hold after mandate',()=>assert.strictEqual(Core.evaluateAiAction({type:'sign_contract',mandateValid:true,humanConfirmed:true}).decision,'HOLD_FOR_FINAL_NAMED_HUMAN_CONFIRMATION'));
t('receipt can be created',()=>{const o=Core.createReceipt(Core.DEFAULT_STATE,'TEST',{a:1});assert.strictEqual(o.state.receipts.length,1);assert.ok(o.receipt.hash);});
t('receipt chain verifies',()=>{let s=Core.createReceipt(Core.DEFAULT_STATE,'A',{}).state;s=Core.createReceipt(s,'B',{}).state;assert.ok(Core.verifyReceipts(s.receipts).valid);});
t('tampered receipt fails',()=>{let s=Core.createReceipt(Core.DEFAULT_STATE,'A',{}).state;s.receipts[0].payload.x=1;assert.ok(!Core.verifyReceipts(s.receipts).valid);});
t('emergency card title',()=>assert.ok(Core.buildEmergencyCard(Core.DEMO_STATE).title.includes('SHENGZHOU')));
t('emergency card has meeting points',()=>assert.strictEqual(Core.buildEmergencyCard(Core.DEMO_STATE).meetingPoints.length,2));
t('drill communication',()=>assert.ok(Core.generateDrill(Core.DEFAULT_STATE,'communication').success.length>=4));
t('drill identity safe boundary',()=>assert.ok(Core.generateDrill(Core.DEFAULT_STATE,'identity').stop.includes('synthetic')));
t('continuity package version',()=>assert.strictEqual(Core.buildContinuityPackage(Core.DEMO_STATE).version,'28.0.0'));
t('continuity package no external action',()=>assert.strictEqual(Core.buildContinuityPackage(Core.DEMO_STATE).boundaries.noExternalAutomaticAction,true));
t('text plan substantial',()=>assert.ok(Core.exportTextPlan(Core.DEFAULT_STATE).length>1200));
t('stable stringify order',()=>assert.strictEqual(Core.stableStringify({b:1,a:2}),Core.stableStringify({a:2,b:1})));
t('hash deterministic',()=>assert.strictEqual(Core.simpleHash('abc'),Core.simpleHash('abc')));
t('high preparedness improves finance',()=>{const a=Core.domainScores(Core.DEFAULT_STATE).finance,b=Core.domainScores(Core.DEMO_STATE).finance;assert.ok(b>a);});
t('AI authority floor responds to controls',()=>{const s=Core.normalizeState(Core.DEFAULT_STATE);Object.assign(s.preparedness,{humanConfirmCritical:true,noAutoTransfer:true,noAutoContract:true,revocationPlan:true,agentInventory:true,leastPrivilege:true});assert.strictEqual(Core.domainScores(s).ai_authority,1);});
t('dependents without routine reduce psychological score',()=>{const s=Core.normalizeState(Core.DEFAULT_STATE);s.profile.children=1;s.preparedness.dependentRoutine=false;assert.ok(Core.domainScores(s).psychological<1);});
t('pets require pet plan',()=>{const s=Core.normalizeState(Core.DEMO_STATE);s.profile.pets=1;s.preparedness.petPlan=false;assert.ok(Core.domainScores(s).mobility<1);});
t('world severity zero removes impact',()=>{const s=Core.normalizeState(Core.DEMO_STATE);s.worlds.find(w=>w.id==='compound_crisis').severity=0;const b=Core.domainScores(s),w=Core.worldResults(s).find(x=>x.id==='compound_crisis');assert.ok(Math.abs(w.scores.finance-b.finance)<1e-9);});
t('world severity one applies impact',()=>{const s=Core.normalizeState(Core.DEMO_STATE);const b=Core.domainScores(s),w=Core.worldResults(s).find(x=>x.id==='compound_crisis');assert.ok(w.scores.finance<b.finance);});
t('priority water action disappears at target',()=>{const s=Core.normalizeState(Core.DEFAULT_STATE);s.preparedness.waterDays=3;assert.ok(!Core.getPriorityActions(s,100).some(a=>a.id==='water3'));});
t('message content not stored in scan output',()=>{const r=Core.scanUrgentMessage('秘密 马上转账');assert.strictEqual(r.text,undefined);});
t('package carries receipts',()=>{let s=Core.createReceipt(Core.DEMO_STATE,'X',{}).state;assert.ok(Core.buildContinuityPackage(s).receipts.length>0);});
t('clamp lower',()=>assert.strictEqual(Core.clamp(-1),0));
t('clamp upper',()=>assert.strictEqual(Core.clamp(2),1));
t('normalize preserves custom name',()=>assert.strictEqual(Core.normalizeState({profile:{displayName:'A'}}).profile.displayName,'A'));
t('unknown AI external action held',()=>assert.ok(Core.evaluateAiAction({type:'unknown',external:true}).decision.startsWith('HOLD')));
t('activation mode has instructions',()=>assert.ok(Core.triggerMode(['official_alert']).instruction.length>20));
t('all emergency modes have actions',()=>{for(let i=0;i<=4;i++)assert.ok(Core.emergencyActions(i).length>=4);});
t('weighted floor bounded',()=>{const x=Core.readinessSummary(Core.DEMO_STATE).weightedFloor;assert.ok(x>=0&&x<=1);});
t('weakest world has three domains',()=>assert.strictEqual(Core.readinessSummary(Core.DEMO_STATE).weakestWorld.weakest.length,3));
console.log(`PASS ${count} JavaScript tests`);
